### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by okawaffles** [GeneralMathematics/General-Mathematics-Beta#9]
example: using `<website>/service/hvtrs8%2F-dksaopd%2Ccmm-lmgkn` (discord login page) the browser refuses to connect and gives a HTTP 404 error.

on chromeos, user agent:
Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by okawaffles** [comment]
CrOS now returns `RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].`

**Comment by moddedstuffguy** [comment]
It does always as Ultraviolet is outdated
